# Config for building https://tmt.readthedocs.io/
version: 2
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    # Pin python version to 3.12 until pint fix is released
    # https://github.com/hgrecco/pint/issues/1969
    python: "3.12"
